### ISSUE TITLE
Any plan to release training code?

### ISSUE THREAD

**Issue by xushangnjlh** [ubc-vision/COTR#1]
RT

**Comment by kmyi** [comment]
We will work on this if/once the paper is accepted ;)

**Comment by Bryce-HJ** [comment]
Excuse me, I want to follow your work and when you can know that your excellent work can be accepted? 
Thanks for your reply~

**Comment by jiangwei221** [comment]
Hi, I'm working on the code releasing currently. Mainly merge the private and the public repo and make sure nothing breaks. Hopefully it can be released in this week.

**Comment by jiangwei221** [comment]
Released
