### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lucifer1002** [ubc-vision/COTR#14]
Hello, when running through the code with the pre-trained model, it appears that RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 7.79 GiB total capacity; 2.90 GiB already allocated; 1.83 GiB free; 4.80 GiB reserved in total by PyTorch).Is there any solution？For example, which parameters to adjust？

**Comment by jiangwei221** [comment]
Have you tried to set the parameter to False? https://github.com/ubc-vision/COTR/blob/682db5a4303a1ecfd5a201709671b593ae0071b0/COTR/inference/inference_helper.py#L19
