### ISSUE TITLE
Can you tell me how to get the evaluation code of the image matching datasets?

### ISSUE THREAD

**Issue by zhirui-gao** [ubc-vision/COTR#17]

**Comment by jiangwei221** [comment]
Hi, we uses a guided matching for the public entry(https://www.cs.ubc.ca/research/image-matching-challenge/2021/submissions/ce67800df501292f-cotr_guided_2048_disk/), and the basic idea is implemented here(
https://github.com/ubc-vision/COTR/blob/master/demo_guided_matching.py).
We use DISK as basic keypoints detector, and uses bidirectional consensus to create matches.
