### ISSUE TITLE
Common view image

### ISSUE THREAD

**Issue by Lucifer1002** [ubc-vision/COTR#20]
Hello, I have the honor to read your article. I would like to ask how to get the common view image after the mask as shown in Figure 4 of the paper according to the mask matrix.

**Comment by jiangwei221** [comment]
Hi, thanks for your interest in our work!
Do you mean how do I obtain mask? To obtain the mask we first estimate the a dense correspondence map from image A to image B. We then feed the predicted target locations in image B as the query points, to get another dense correspondence map from B to A. It allows us to compute the cycle consistency, and we simply mask out areas with high cycle consistency error.
If our network is perfect, the `Target=f(Query)` and `f(f(Query))=Query`, and it means 0 cycle consistency error.
You can check these two lines to see how we obtain the masks: https://github.com/ubc-vision/COTR/blob/21c31ed32b5db1a8196a5a994a7ef1af82fc2015/COTR/inference/sparse_engine.py#L142-L143
