### ISSUE TITLE
Match time

### ISSUE THREAD

**Issue by Lucifer1002** [ubc-vision/COTR#21]
Hello, about COTR, if I use other feature extraction methods to get the feature point positions of the image and input them, can I reduce the time of COTR feature matching?

**Comment by jiangwei221** [comment]
Hi, unfortunately known feature point positions won't reduce the matching time. You can check our guided matching demo here: https://github.com/ubc-vision/COTR/blob/master/demo_guided_matching.py, where we used DISK as the key point location.
If you have the feature, you can also try to use SuperGlue as the matcher.
