### ISSUE TITLE
Rotation angle

### ISSUE THREAD

**Issue by Lucifer1002** [ubc-vision/COTR#26]
Hello, I would like to ask, when COTR extracts the common view area, for some scenes with too large rotation angle, the formula area cannot be extracted. What is the possible reason for this phenomenon?

**Comment by jiangwei221** [comment]
Hi, we tested the common area with different angles, and indeed that when rotation angles increases, the performance decreases. One possible reason is that we didn’t do data augmentation during training, and the trained network is robust to in-plane rotation.
