### ISSUE TITLE
How to get depth map

### ISSUE THREAD

**Issue by shizukasonn** [ubc-vision/COTR#27]
Hi, thank you for your nice work:)
Sorry I'm new to this filed, I wonder how can I get the depth map of two images using COTR results?
thanks a lot

**Comment by jiangwei221** [comment]
Hi, to obtain the depth map, you need to triangulate the 3D points using the correspondences, which requires known camera poses and camera intrinsics.
Once the 3D points are obtained, you can project those points to the two cameras and obtain 2 depth maps.
There is a demo program in the repo that shows how to do this 3D points triangulation.
