### ISSUE TITLE
Dense optical flow as in paper Figure 1 (c)

### ISSUE THREAD

**Issue by Wuziyi616** [ubc-vision/COTR#28]
Hi, thanks for the great work! I wonder how can I estimate the optical flow between two images. Say img1 is of shape [H, W], then can I basically reshape the grid coordinates to [H*W, 2] and then input to `queries_a` as in this [demo](https://github.com/ubc-vision/COTR/blob/bcc9ce7451443e7c8c329a51e539f6833c15695d/demo_homography.py#L44)?

**Comment by Wuziyi616** [comment]
Another question is that, what does `force` [here](https://github.com/ubc-vision/COTR/blob/bcc9ce7451443e7c8c329a51e539f6833c15695d/COTR/inference/sparse_engine.py#L197) mean?

**Comment by jiangwei221** [comment]
Hi, you can try to use `demo_single_pair.py` which will triangulate a dense optical flow based on the sparse points. Directly reshaping the grid coordinates and feed it as input will be computational expensive.
`force` argument outputs correspondences for all the input points, and avoid the drifting check.

**Comment by Wuziyi616** [comment]
Thanks for your prompt reply. That makes a lot of sense
