### ISSUE TITLE
How is the warpped image in Figure 9 generated?

### ISSUE THREAD

**Issue by Wuziyi616** [ubc-vision/COTR#31]
Hi, thanks for the great work! I'm curious about how do you generate the warpped image in Figure 9 by dense flow. If I understand correctly, you input a pixel coordinate (x, y) in img1, and get its corresponding coordinate (x', y') in the img2. Then, you just copy the RGB in (x, y) to (x', y') in img2, and repeat this for all the coordinates in img1. Am I correct? Or, is there any efficient way of doing so? (like you've mentioned in #28 ?)

**Comment by jiangwei221** [comment]
Hi, I think the dense flow of Fig9 is generated at 256x256 resolution, which is the coarsest result from COTR.
You can obtain the flow and the resampled images from this line: https://github.com/ubc-vision/COTR/blob/bcc9ce7451443e7c8c329a51e539f6833c15695d/COTR/inference/sparse_engine.py#L131

**Comment by Wuziyi616** [comment]
Thanks for the quick reply, and correct me if I'm wrong: from [this line](https://github.com/ubc-vision/COTR/blob/bcc9ce7451443e7c8c329a51e539f6833c15695d/COTR/inference/inference_helper.py#L120), it seems that the input query coordinate of your model can be either in I or I'? If that's true the warping image is the same as people do in e.g. optical flow, and I understand the process.

**Comment by jiangwei221** [comment]
Yes, the query coordinate can be either in I or I'.

**Comment by Wuziyi616** [comment]
Thanks for the reply! That helps a lot.
