### ISSUE TITLE
find the coordinates of the corresponding point (x', y') on another picture.

### ISSUE THREAD

**Issue by lllllialois** [ubc-vision/COTR#39]
Thank you for the outstanding work you do. I would like to ask if it is possible to enter the coordinates of a point (x, y) and find the coordinates of the corresponding point (x', y') on another picture.

**Comment by jiangwei221** [comment]
Yes, it is possible. You can check the script: https://github.com/ubc-vision/COTR/blob/master/demo_homography.py
In this script we manually input the coordinates of 4 corners of a paint, and find corresponding points in the other image.

**Comment by lllllialois** [comment]
> 

Thank you very much for your prompt answer, I have tried your suggestion and was able to find the coordinates of the corresponding feature points.
Also, can cotr be used for matches with large deformations? For example, a photo of the same person with five fingers open and a photo of the same person with five fingers together, or a photo of a different person with the same five fingers open.

**Comment by lllllialois** [comment]
> Yes, it is possible. You can check the script: https://github.com/ubc-vision/COTR/blob/master/demo_homography.py In this script we manually input the coordinates of 4 corners of a paint, and find corresponding points in the other image.

I tried, but when I specified a point and tried to find its counterpart, I entered the fixed image coordinates and the resulting content of the corresponding point coordinates did not match the original image, it seemed to just move the fixed image coordinate set uniformly to the floating image.

**Comment by jiangwei221** [comment]
Maybe the images you tested are too difficult for COTR to work, I.e too much deformation. Can you share some screenshots of your test images?

**Comment by lllllialois** [comment]
> Maybe the images you tested are too difficult for COTR to work, I.e too much deformation. Can you share some screenshots of your test images?

I tried it again this morning and replaced the function 'cotr_corr_multiscale_with_cycle_consistency' with 'cotr_corr_multiscale ' and it worked a little better. When using 'cotr_corr_multiscale_with_cycle_consistency' I enter five coordinates and end up with only one set of matches, using 'cotr_corr_multiscale ', I was able to find all of them, although there were some wrong matches in there.
![findxyhand12](https://user-images.githubusercontent.com/105269874/189015543-f0838fc5-c799-4d25-a3f0-358f6a7ed32e.png)
![findxy12](https://user-images.githubusercontent.com/105269874/189015556-06754257-75e3-4772-8751-5ef300d55f70.png)
The image above is generated using the function 'cotr_corr_multiscale_with_cycle_consistency' and the image below is generated using 'cotr_corr_multiscale'.
I also tried matching photos of different hands and the results are shown below.
![differentpeoplezijifind](https://user-images.githubusercontent.com/105269874/189018194-baec1b51-108c-429b-bf5e-8f875e47476c.png)
From the naked eye, the effect seems to be OK.

**Comment by jiangwei221** [comment]
Yes, the one with cycle consistency will filter out matches that are not trustworthy, that’s why you only obtained one match in the end.

**Comment by lllllialois** [comment]
thanks for ur answer！

**Comment by lllllialois** [comment]
Although it doesn't feel quite possible, I'd like to ask if you think cotr can be used for point cloud alignment.

**Comment by klinic** [comment]
> > Maybe the images you tested are too difficult for COTR to work, I.e too much deformation. Can you share some screenshots of your test images?
> 
> I tried it again this morning and replaced the function 'cotr_corr_multiscale_with_cycle_consistency' with 'cotr_corr_multiscale ' and it worked a little better. When using 'cotr_corr_multiscale_with_cycle_consistency' I enter five coordinates and end up with only one set of matches, using 'cotr_corr_multiscale ', I was able to find all of them, although there were some wrong matches in there. ![findxyhand12](https://user-images.githubusercontent.com/105269874/189015543-f0838fc5-c799-4d25-a3f0-358f6a7ed32e.png) ![findxy12](https://user-images.githubusercontent.com/105269874/189015556-06754257-75e3-4772-8751-5ef300d55f70.png) The image above is generated using the function 'cotr_corr_multiscale_with_cycle_consistency' and the image below is generated using 'cotr_corr_multiscale'. I also tried matching photos of different hands and the results are shown below. ![differentpeoplezijifind](https://user-images.githubusercontent.com/105269874/189018194-baec1b51-108c-429b-bf5e-8f875e47476c.png) From the naked eye, the effect seems to be OK.

Excuse me, do you mean a single pixel or a very small area on the hand. Because I consider that a single pixel has no coordinates of four corners
