### ISSUE TITLE
why scipy imresize

### ISSUE THREAD

**Issue by ducha-aiki** [ubc-vision/COTR#4]
Hi,

Any reason to prefer scipy version over OpenCV, skimage or PIL?

**Comment by kmyi** [comment]
I don't think so. @jiangwei221 why not PIL (which is my favourite). @ducha-aiki Is the version Wei using having any bugs here?

**Comment by ducha-aiki** [comment]
No idea - I am trying to run it locally on my laptop, where I cannot install required scipy version. So far I am replacing it with skimage.transform.resize and  skimage.transform.rescale in order to run it.

**Comment by ducha-aiki** [comment]
It works with skimage, at least on the handlabeled keypoints from the WxBS  ground truth ;) and I managed to run it without cuda! 

<img width="275" alt="image" src="https://user-images.githubusercontent.com/4803565/126366426-4d3f1b69-195c-4462-8ddd-7ef5bcfccad0.png">

**Comment by jiangwei221** [comment]
Hi, I've removed the dependency on misc.imresize, and replaced with cv2.resize. There is no specific reason that I choose imresize over others. I checked the values for both uin8 resize and float number resize, and the numbers match.

**Comment by jiangwei221** [comment]
Nah, cv2.resize != misc.imresize. My previous check must be wrong.

**Comment by jiangwei221** [comment]
Moved to PIL
