### ISSUE TITLE
glfw on headless machine

### ISSUE THREAD

**Issue by PruneTruong** [ubc-vision/COTR#6]
Hi, thanks for the great work! I am trying to run the code on a headless server but I get an error with glfw: 
ends/_glfw.py", line 215, in _vispy_get_native_app                                                  
    raise OSError('Could not init glfw:\n%r' % _glfw_errors)                                        
OSError: Could not init glfw:                                                                       
["Error 65544: b'X11: Failed to open display '"]. 

I did some research, and it seems that glfw does not support headless rendering. Have you ever tried it?

**Comment by jiangwei221** [comment]
You can try to run the EGL headless examples from vispy here: https://github.com/vispy/vispy/tree/main/examples/offscreen
(I don't have sudo to install `libgles2-mesa-dev` on my server.)
If EGL backend works for your server, then you can modify `inference_helper.py`, and switch glfw to EGL.
Also something from vispy: https://vispy.org/faq.html#how-to-render-headless-off-screen-with-vispy
